<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYm46CRV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYm46CRV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYm46CRV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYm46CRV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYm46CRV\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ym46CRV',
    'container.build_id' => '9be9d505',
    'container.build_time' => 1616298918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYm46CRV');
